### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by cresswellkg** [gersteinlab/HiC_spector#2]
I have been receiving the error `TypeError: 'float' object cannot be interpreted as an integer` trying to calculate the reproducible score using data of the same form as the data included below:

16000000	16000000	39
16000000	16500000	16
16500000	16500000	1461

The code that I am running is the following:

 `python run_reproducibility_v2.py t primary.chr22.500000.txt replicate.chr22.500000.txt 500000`

# Full Traceback

Traceback (most recent call last):
  File "run_reproducibility_v2.py", line 203, in <module>
    main()

  File "run_reproducibility_v2.py", line 190, in main
    M1, M2=Parse_matrix_lieberman(sys.argv[2],sys.argv[3],int(sys.argv[4]))

  File "run_reproducibility_v2.py", line 63, in Parse_matrix_lieberman
    M1=lil_matrix((max_index,max_index))

  File "C:\Users\Kelis\Anaconda3\lib\site-packages\scipy\sparse\lil.py", line 108, in __init__
    self.rows = np.empty((M,), dtype=object)

TypeError: 'float' object cannot be interpreted as an integer

**Comment by cresswellkg** [comment]
I managed to fix the error by adding the line `max_index = int(max_index)` after `max_index=max_index/resolution+1` in the function Parse_matrix_lieberman.
